<a href="https://colab.research.google.com/github/mobkimark/Darked/blob/master/HDSC_INTERNSHIP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [ ]:
a.shape

(3, 5)

In [ ]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
b = a.reshape (5,3, 1)

In [ ]:
print(b)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]

 [[13]
  [14]
  [15]]]


In [ ]:
np.random.randint(99,100)

99

In [ ]:
np.random.randint(100, size = (5, 6))

array([[75,  7, 39, 31,  3, 73],
       [96, 22, 83, 87, 96,  2],
       [40, 81,  6, 62, 41, 38],
       [90, 33, 50, 27, 62, 38],
       [52,  5, 99, 50, 40, 19]])

In [ ]:
np.random.binomial(n=2, p=0.5, size=10)

array([1, 0, 2, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
np.random.normal(loc = 2, scale =4, size=10)

array([ 1.3682078 , -5.11441584,  7.04061212,  1.87006459, -1.94344827,
        8.33744741,  5.0615892 ,  7.56826255,  0.17319621, -1.59021943])

In [ ]:
np.mean([1,2,3,4,5])

3.0

In [ ]:
np.mean(np.random.normal(loc = 2, scale =4, size=10))

3.566807527269355

In [ ]:
b.shape

(5, 3, 1)

In [ ]:
print(b)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]

 [[13]
  [14]
  [15]]]


In [ ]:
c = b.reshape (1,3,5)

In [ ]:
print(c)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [ ]:
c*2

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20],
        [22, 24, 26, 28, 30]]])

In [ ]:
c=c*2

In [ ]:
print(c)

[[[ 2  4  6  8 10]
  [12 14 16 18 20]
  [22 24 26 28 30]]]


In [ ]:

import pandas as pd


In [ ]:
pd

<module 'pandas' from '/usr/local/lib/python3.10/dist-packages/pandas/__init__.py'>